### ISSUE TITLE
The generated effect will change the original image

### ISSUE THREAD

**Issue by centerqi** [iuliaturc/detextify#17]
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/2747472/208032081-6d710906-7880-4e30-91d2-ab60dac1df74.png">

**Comment by iuliaturc** [comment]
Thanks for flagging this!

This happens with the Stable Diffusion in-painters when the input image is larger than 512 x 512. We split the image into multiple tiles, and call in-painting on the tiles with text (in your case, top-left tile). Unfortunately, SD changes the colors a little bit (despite the mask), hence the effect that you're seeing.

We should think of work-arounds though, so I'll leave this issue open as a feature request.

In the meantime, if you want to avoid this effect, you can use the DalleInapinter, which accepts images larger than 512 x 512, and we don't need to perform tiling.

**Comment by centerqi** [comment]
Thanks for your reply, I have an idea that might be more efficient.
1. Direct OCR to find the position of the text.
2. Carry out color segmentation of text blocks.
3. Generate a mask.
4. Direct inpaint

**Comment by scruffynerf** [comment]
this might also be the jpeg conversion you're doing.  See issue #19

**Comment by iuliaturc** [comment]
@centerqi Submitted [a fix](https://github.com/iuliaturc/detextify/commit/01f8a67309903dbbcf54a5beb193a34d21d89ffd) to only replace the in-painted text boxes, instead of the entire tiles. This doesn't fix the underlying problem (edges are still visible), but in practice it's less jarring for a lot of images.

@scruffynerf The conversion only happens for the ReplicateSDInpainter (not the local one), so it doesn't fully justify the discrepancy. Thanks for looking into it though!

Before
---
(edges visible across the entire image)
![octopus_100steps](https://user-images.githubusercontent.com/6214514/210628410-10cb7c8b-d698-41c8-b785-ed0bfae2f263.png)
e):

After
---
(edge still visible top-center, but less jarring):
![octopus_detext](https://user-images.githubusercontent.com/6214514/210628171-656e0a8d-32bb-474a-bac5-c675fffb014a.png)
